honeycombio/gritql

- crates/cli/src/messenger_variant.rs
It is not possible to enforce clippy for the server feature in this repo because it doesn't build at all.
> fix: cli server clippy error

- crates/core/src/pattern/function_definition.rs
- crates/util/src/runtime.rs
hides some wasm specific features behind arch wasm32, so they don't break the build due to conflicting feature flags
> fix: wasm feature doesn't break build

- Cargo.lock
- crates/cli/Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/lib.rs
Removes unused crates in Marzano core, and adds a lint that forbids them
> chore: forbid unused crates in core

- Cargo.lock
- crates/auth/Cargo.toml
- crates/core/src/lib.rs
- crates/externals/Cargo.toml
- crates/gritcache/Cargo.toml
- crates/gritmodule/Cargo.toml
- crates/language/Cargo.toml
- crates/lsp/Cargo.toml
- crates/lsp/src/scan.rs
- crates/marzano_messenger/Cargo.toml
- crates/test_utils/Cargo.toml
- crates/util/Cargo.toml
forbids unused crates in all but wasm-bindings and cli
> Chore: Forbid unused crates

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/lib.rs
- crates/cli_bin/Cargo.toml
- crates/cli_bin/src/main.rs
adds a lint to clil and cli_bin crate to enforce no unused dependencies in cargo.toml
> chore: remove unused cli deps

- crates/auth/Cargo.toml
- crates/cli/Cargo.toml
- crates/cli_bin/src/main.rs
- crates/core/Cargo.toml
- crates/externals/Cargo.toml
- crates/gritcache/Cargo.toml
- crates/gritmodule/Cargo.toml
- crates/language/Cargo.toml
- crates/lsp/Cargo.toml
- crates/marzano_messenger/Cargo.toml
- crates/test_utils/Cargo.toml
- crates/util/Cargo.toml
- crates/wasm-bindings/Cargo.toml
tests are compiled independently so can result in false positives when enforcing this lint, warn is sufficient to fail CI.
> chore: warn instead of forbid unused crate

- README.md
We should showcase how powerful GritQL is by including links to complex examples.
> chore: add complex examples in docs

- .github/workflows/release-plz.yaml
Previous release job failed, looks like due to a lack of the submodules: https://github.com/getgrit/gritql/actions/runs/8908198285/job/24463410476
Hopefully this fixes it.
> chore: checkout submodules for release

- crates/core/src/test.rs
- crates/language/src/python.rs
We already have logic for handling orphaned commas, but it didn't handle cases where they come at the end of the statement. This is now fixed.
> fix(py): remove trailing commas in short import statements

- crates/cli/Cargo.toml
Follow up to https://github.com/getgrit/gritql/pull/349, which accidentally broke Windows builds.
> fix: move fs_err to normal dep

- .release-plz.toml
We use GitHub releases for distributing the Grit binary, so release-plz should not be used for this purpose. Crates are sufficient.
> chore: disable releases on GitHub

- crates/cli/src/commands/apply_migration.rs
- crates/cli/src/result_formatting.rs
- crates/cli/src/workflows.rs
- crates/marzano_messenger/src/emit.rs
So we can report the fully summary, it's helpful to report the full outcome back instead of just success.
> feat: deliver workflow outcomes to cloud

- crates/gritmodule/src/fetcher.rs
We previously naively grabbed the first remote listed, now we do something smarter:
- First prefer the tracking remote for current branch
- Then look for a repo named origin
- Fall back to first one
> fix: correctly handle repos with multiple origins

- crates/core/src/ast_node.rs
- crates/core/src/lazy.rs
- crates/core/src/pattern_compiler/compiler.rs
- crates/core/src/stateless.rs
- crates/grit-pattern-matcher/src/pattern/contains.rs
Make sure we can do `binding.match("console.log")`.
Follow up from https://github.com/getgrit/gritql/pull/512
> fix: make compound snippets work with stateless compiler

- python/gritql/installer.py
- Updated the platform variable to map correctly to the valid release download URLs based on the operating system (macOS).
- AS-IS
https://github.com/getgrit/gritql/releases/latest/download/marzano-aarc64-macos.tar.gz
- TO-BE
https://github.com/getgrit/gritql/releases/latest/download/marzano-aarc64-apple-darwin.tar.gz
#515
> fix: change download url for darwin

- Cargo.lock
- crates/cli/src/analyze.rs
- crates/cli/src/commands/apply_pattern.rs
- crates/core/Cargo.toml
- crates/core/src/lib.rs
- crates/core/src/marzano_context.rs
- crates/core/src/marzano_resolved_pattern.rs
- crates/core/src/pattern_compiler/auto_wrap.rs
- crates/core/src/pattern_compiler/compiler.rs
- crates/core/src/pattern_compiler/pattern_compiler.rs
- crates/core/src/pattern_compiler/snippet_compiler.rs
- crates/core/src/sdk/binding.rs
- crates/core/src/sdk/compiler.rs
- crates/core/src/sdk/language_sdk.rs
- crates/core/src/sdk/lazy.rs
- crates/core/src/sdk/mod.rs
- crates/core/src/sdk/pattern_sdk.rs
- crates/core/src/sdk/test_js.rs
- crates/grit-pattern-matcher/src/pattern/file_pattern.rs
- crates/grit-pattern-matcher/src/pattern/patterns.rs
- crates/language/src/target_language.rs
- crates/marzano_messenger/src/emit.rs
- crates/util/src/rich_path.rs
- crates/wasm-bindings/index.html
- crates/wasm-bindings/package.json
- crates/wasm-bindings/src/match_pattern.rs
Proof of concept verification for the SDK.
https://github.com/getgrit/gritql/issues/484
> feat: basic builder API for SDK

- crates/core/src/lib.rs
- crates/core/src/pattern_compiler/ast_node_compiler.rs
- crates/core/src/test_errors.rs
If the node doesn't accept any field parameters, make that clearer.
> fix: improve error for nodes with invalid fields

- crates/core/src/optimizer/hoist_files.rs
- crates/core/src/optimizer/hoist_text.rs
- crates/core/src/optimizer/mod.rs
- crates/core/src/pattern_compiler/auto_wrap.rs
- crates/core/src/pattern_compiler/file_owner_compiler.rs
- crates/grit-pattern-matcher/src/pattern/variable.rs
Take a similar approach to https://github.com/getgrit/gritql/pull/306
This optimizer pass is fairly effective, since a quick string search on the file is an order of magnitude faster than traversing the AST.
Note we don't actually skip parsing (yet), just traversal.
Note that right now the only cases actually extracted are explicitly matched against $body, like:
```
`funcify` where {
$program <: contains `console`
}
```
This becomes:
```
file(body=and {
includes "console",
contains `funcify` where {
$program <: contains `console`
}
})
```
> feat: add a basic optimizer pass for contains

- crates/core/src/problem.rs
- crates/grit-pattern-matcher/src/pattern/state.rs
> chore: use `&Path` in `FileRegistry::new_from_paths()`

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/commands/format.rs
- crates/cli/src/commands/mod.rs
- crates/cli/src/commands/patterns_test.rs
- crates/cli/src/result_formatting.rs
- crates/cli_bin/fixtures/go/imports.grit
- crates/cli_bin/tests/format.rs
- crates/core/src/api.rs
Finish https://github.com/getgrit/gritql/pull/595
- Make it look nice
- Fix massive memory usage / terrible perf
> fix: make format work better

- crates/cli/src/commands/format.rs
- crates/core/src/lib.rs
- crates/core/src/sdk/compiler.rs
- crates/core/src/sdk/language_sdk.rs
- crates/core/src/sdk/mod.rs
- crates/core/src/sdk/pattern_sdk.rs
- crates/core/src/sdk/snapshots/marzano_core__sdk__test_yaml__tests__rewrite.snap
- crates/core/src/sdk/test_yaml.rs
Hopefully makes the yaml less error-prone, follow up to https://github.com/getgrit/gritql/pull/606.
> chore: use native pattern builder instead of string interpolation

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/commands/format.rs
- crates/cli_bin/tests/format.rs
- crates/cli_bin/tests/snapshots/format__format_patterns_with_rewrite-2.snap
- crates/cli_bin/tests/snapshots/format__format_patterns_with_rewrite-3.snap
- crates/cli_bin/tests/snapshots/format__format_patterns_with_rewrite-4.snap
- crates/cli_bin/tests/snapshots/format__format_patterns_with_rewrite-5.snap
- crates/cli_bin/tests/snapshots/format__format_patterns_with_rewrite-6.snap
- crates/cli_bin/tests/snapshots/format__format_patterns_with_rewrite.snap
- crates/core/Cargo.toml
Make the exit code 0 when format is clean, for use in CI.
> fix: refine `grit format` exit code

- crates/cli_bin/tests/apply.rs
- crates/core/src/limits.rs
Introduce a `GRIT_MAX_FILE_SIZE_BYTES` env variable that can be used to tune the limit of files that Grit will skip.
Set it to `0` to skip the limit entirely.
Fixes https://github.com/getgrit/gritql/issues/614
> feat: allow overriding max file size limit

- docs/src/pages/discord.mdoc
Next.js deployed on GitHub pages doesn't support redirects so this is the simplest solution.
> fix: add Discord page
